
#---------------------#
# Example config.yaml #
#-------------------- #
- name: current-weather-home

  source:
  
    name: openweathermap
    poll_interval: 10m
    latitude: 45.45
    longitude: 75.75
    apikey: ${OWM_APIKEY}
    units: metric
    language: en

  destinations:

    - # report to Influxdb
      name: influxdb2
      fields: [ temperature, relative_humidity ]

      # Influxdb2 specific config:
      token: ${INFLUXDB_TOKEN}
      host: http://192.168.50.2:8086
      org: home
      bucket: weather
      measurement: weather.metric
      tags:
         location: home
    
    - # report to mqtt broker
      name: mqtt
      fields: [ temperature, relative_humidity, cloud_cover, summary ]

      # mqtt specific config:
      user: ${MQTT_USER}
      pass: ${MQTT_PASS}
      persist: false
      host: http://192.168.50.2:4568
      topic: home/weather/current/${field}
      will:
         topic: home/weather/current/status
         value: offline
